spring:
  application:
    name: spring-kafka-demo-confluent
  kafka:
    bootstrap-servers: pkc-56d1g.eastus.azure.confluent.cloud:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='OHB7VDEFXW6XZTL7' password='7dw0II8b0Z3mUE1QhHyK3BMTrRF3j9ZTsy3Vjc9ZaS69HC+zlEkRyQs59LrDu+qj';
      security:
        protocol: SASL_SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
