spring:
  application:
    name: spring-kafka-demo-confluent
  kafka:
    bootstrap-servers: pkc-56d1g.eastus.azure.confluent.cloud:9092
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='WKUZKZ5O3SZGOU2B' password='5I+5/QCUgszbL64kz6gdArbVZOn/M52etZO5SjN21l/l2lHjyEvNz1wbZAyEt+Vn';
      security:
        protocol: SASL_SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
